ci:
    autofix_commit_msg: |
        Pre-commit autofix 

        Pre-commit CI got your back!
    autofix_prs: true
    autoupdate_branch: "trunk"
    autoupdate_commit_msg: "Pre-commit weekly update"
    autoupdate_schedule: weekly
    skip: []
    submodules: false

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        files: ^backend/
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.10
        args:
        - --config=backend/pyproject.toml
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        args:
        - --settings-path=backend/pyproject.toml
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.4
    hooks:
    -   id: pylint
        args:
        - --rcfile=backend/pyproject.toml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
    -   id: mypy
        args:
        - --config-file=backend/pyproject.toml
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
    -   id: check-pre-commit-ci-config
