coverage:
  status:
    project: False
    patch: False

flag_management:
  individual_flags:
    - name: backend
      paths:
        - backend/
      statuses:
        - type: project
          target: 90%
          threshold: 1%
#    - name: frontend
#      paths:
#        - frontend/
#      statuses:
#        - type: project
#          target: 85%
#          threshold: 1%
