version: '3.8'

services:

  db:
    image: postgres:14.2-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/iW_db
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db/iW_test
    ports:
      - 8000:8000
    depends_on:
      - db
